spring:
  profle:
    ## (1)
    active: dev
---
spring:
    ## (2)
    profiles: dev
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:/tmp/customers;MODE=PostgreSQL
      username: sa
      password:
    jpa:
      database: H2
      hibernate:
        ddl-auto: create-drop
---
spring:
    ## (3)
    profiles: heroku
    datasource:
      driverClassName: org.postgresql.Driver
    jpa:
      database: POSTGRESQL
      hibernate:
        ddl-auto: create-drop